# 1. Main Context (Global settings)
#user nginx;

# 2. Events Context (Mandatory, even if empty!)
#events {
    # worker_connections 1024;
#}

# 3. HTTP Context
#http {
    # ... global http settings ...

    # 4. Server Context (This is where your 'server' block goes)
    server {
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        root /var/www/wordpress;
        index index.php index.html index.htm;
        server_name localhost;
        location / {
            try_files $uri $uri/ =404;
        }
        #location ~ \.php$ {
        #    include snippets/fastcgi-php.conf;
        #    fastcgi_pass wordpress:9000;
        #}
    }
#}