services:
  mariadb:
    secrets:
    - source: mariadb_password
      target: mariadb_password.txt
    - source: mariadb_root_password
      target: mariadb_root_password.txt
    container_name: MariaDB
    networks:
      - inception
    image: "inception/mariadb"
    build:
      context: services/mariadb
      dockerfile: Dockerfile
    env_file:  .env
    volumes:
      - mariadb:/var/lib/mysql #${DB_PATH}
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    secrets:
      - source: inception_crt  # Reference the name defined below
        target: inception.crt
      - source: inception_key
        target: inception.key
    container_name: NGINX
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: services/nginx
      dockerfile: Dockerfile
    env_file: .env
    image: "inception/nginx"
    ports:
      - "443:443"
    restart: unless-stopped

  wordpress:
    secrets:
      - source: wordpress_password
        target: wordpress_password.txt
      - source: wordpress_root_password
        target: wordpress_root_password.txt
      - source: mariadb_password
        target: mariadb_password.txt
    container_name: WordPress
    volumes:
      - wordpress:/var/www/wordpress #${WP_PATH}
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: services/wordpress
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "9000"
    image: "inception/wordpress"
    restart: unless-stopped

  static_website:
    container_name: StaticWebSite
    networks:
      - inception
    build:
      context: services/bonus/static_website
      dockerfile: Dockerfile
    expose:
      - "8080"
    image: "inception/static_website"
    restart: unless-stopped

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yroard/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yroard/data/mariadb'
  static_website:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yroard/data/static_website'

networks:
  inception:
    driver: bridge

secrets:
  mariadb_password: #MYSQL_PASSWORD
    file: ../secrets/mariadb_password.txt
  mariadb_root_password: #MYSQL_ROOT_PASSWORD
    file: ../secrets/mariadb_root_password.txt
  wordpress_password: #WP_USER_PASSWORD
    file: ../secrets/wordpress_password.txt
  wordpress_root_password: #WP_ADMIN_PASSWORD
    file: ../secrets/wordpress_root_password.txt
  inception_crt:
    file: ../secrets/inception.crt
  inception_key:
    file: ../secrets/inception.key
