version: "3" #permet de savoir

services: 
mariadb:
  image: "inception/mariadb"
    build: requirements/
      Dockerfile: "../services/mariadb/Dockerfile"
  volumes:
    - "mariadb:" #a completer, on ne sait pas encore ou monter ce volume dans le conteneur
  restart: always
nginx:
  image: "inception/nginx"
    build:
      Dockerfile: "../services/nginx/Dockerfile" 
  ports:
    - "443:443:tcp" #port de reception de la machine hote/sur quel port tu transferes ce trafic
  restart: always
wordpress:
  image: "inception/wordpress"
    build:
      Dockerfile: "../services/wordpress/Dockerfile"
  volumes:
    - "wordpress:"
    restart: always

etwork
volumes:
  mariadb:
  wordpress: