server {
    server_name yroard.42.fr;
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /run/secrets/inception.crt;
    ssl_certificate_key /run/secrets/inception.key;

    root /var/www/wordpress;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
    location ~ \.php$ {
        include /etc/nginx/fastcgi.conf;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
server {
    server_name static.yroard.42.fr;
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /run/secrets/inception.crt;
    ssl_certificate_key /run/secrets/inception.key;

    location /{
        proxy_pass http://static_website:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}