# # 1. Main Context (Global settings)
# user nginx;
#
# # 2. Events Context (Mandatory, even if empty!)
# events {
#     worker_connections 1024;
# }
#
# http {
#     include /etc/nginx/mime.types;
#     default_type application/octet-stream;

    # 4. Server Context (This is where your 'server' block goes)
    server {
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        root $WP_PATH;
        index index.php index.html index.htm;
        server_name localhost;
        location / {
            try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
            #include snippets/fastcgi-php.conf;
            include /etc/nginx/fastcgi.conf;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
#}